image: macos-mojave

# scripts that run after cloning repository
install:

# scripts to run before build
before_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - sh build.sh

# scripts to run after build (working directory and environment changes are persisted from the previous steps)
after_build:

